### PR TITLE
Picopass more bit formats

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Remove parsing of 26 bit credentials since it didn't check parity and could have been wrong
- Support more LFRFID formats for longer bit length credentials

# Verification 

- Part 1. Scan a 26 bit credential, see that it shows the raw value and not a facility code or card number
- Part 2. Scan a credential that is longer than 26 bits, see that you can save as LFRFID

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by bettse** [comment]
converting to draft: I was porting the changes to seader and a 35bit card wasn't working as expected, so I want to check more credential sizes first

**Comment by bettse** [comment]
Ready for review, it was just the differences in the "Data: xxx" that were throwing me, but LFRFID emulation and a proxmark show the expected data.

**Comment by skotopes** [comment]
@bettse should I wait for changelog or it's ok to merge?

**Comment by bettse** [comment]
ok to merge 👍 : we'll (probably) do a changelog + version bump PR after this.  We might do one more, we're talking about maybe adding haptics to loclass.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
