### PR TITLE
Picopass cleanup

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Now that we have some block validation and auth method, using them in the read success and card menu

# Verification 

- Try reading any picopass or iclass card.  It should present reasonable information and reasonable save suggestions.  No significant changes in information, but the credential is now bold where less important information is below it.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by bettse** [comment]
this is ready to be looked at when someone has time

**Comment by skotopes** [comment]
@bettse I'll merge it in a couple days

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
Sorry for delay, got cold last week.

**Comment by bettse** [comment]
No problem!

**Pull request merged**
