### PR TITLE
Update MFKey to v3.0

### PR DESCRIPTION
**Pull request by noproto**
# What's new

This pull request only serves to track changes (as the source may be relocated for OFW 1.1).

- Added Static Encrypted Nested key recovery
- Added NFC app support
- Dropped FlipperNested support

# Verification

Using PR 3822: https://github.com/flipperdevices/flipperzero-firmware/pull/3822

- Acquire weak PRNG MIFARE Classic tag with unknown keys.
- Open NFC app.
- Select "Read" and hold the Flipper Zero against the tag. Wait until tag is fully read.
- Open MFKey manually/select "Recover keys" in NFC app.
- Press center button on Flipper to initiate key recovery. **New keys must be found in this step.**
- Return to NFC app and select "Read". Wait until tag is fully read.
- **Confirm all keys are found on tag.**

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by noproto** [comment]
~~Reviewing PR to PR branch https://github.com/noproto/flipperzero-good-faps/pull/1~~ Merged.

**Comment by noproto** [comment]
Reference for moving MFKey into firmware: https://github.com/noproto/xero-firmware/commit/619445da4b30afa004db0dab289e1bbe74cfaa48#diff-c69d1c7bbadc50c19f88bb188ae66d42b27ba06880ad2bcd2c72635f485da30a

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
I'm a little confused.

Where will be main repository for this application? Here? Firmware? Your repository?

From firmware standpoint the best place is main firmware repository, but we also can have it as submodule.

**Comment by skotopes** [comment]
I'll put it into draft mode since APIs needed for this app is missing

**Comment by noproto** [comment]
> I'm a little confused.
> 
> Where will be main repository for this application? Here? Firmware? Your repository?
> 
> From firmware standpoint the best place is main firmware repository, but we also can have it as submodule.

Firmware. I opened this PR when the changes were being developed in case there was feedback, it could be discussed here. Now that https://github.com/flipperdevices/flipperzero-firmware/pull/3943 is open, development has moved there. If and when 3943 is merged, mfkey can be deleted from the good-faps repository and the catalog.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
