### PR TITLE
Replace Mfkey32 with MFKey

### PR DESCRIPTION
**Pull request by noproto**
# What's new

- Added Nested key recovery
- Use new KeysDict API
- Fix crashes
- More efficient RAM utilization
- Faster (hand-optimized the assembly of the evenparity32 function for the Cortex M4F/STM32)

# Verification 

The following Mfkey32 nonces can be used to test this version of MFKey, stored at /ext/nfc/.mfkey32.log:

```
Sec 0 key A cuid 35f27499 nt0 dab7690b nr0 b37582d9 ar0 cb7feff4 nt1 7925a33b nr1 8202f643 ar1 7fff9938
Sec 0 key A cuid 35f27499 nt0 f6f97a65 nr0 dd921968 ar0 d9416faa nt1 b0625f07 nr1 2b61e607 ar1 11194bd4
Sec 0 key A cuid 35f27499 nt0 88b03ffd nr0 0191cd9c ar0 d628ca2c nt1 8b95f42c nr1 84937343 ar1 7ec13b02
Sec 0 key A cuid 35f27499 nt0 6fc76292 nr0 c94c25be ar0 a5be9f0f nt1 acc78f1a nr1 0ca3f487 ar1 793e90c0
Sec 0 key A cuid 35f27499 nt0 c234cc74 nr0 aea5a31d ar0 3135fee3 nt1 2c8023a6 nr1 9d148a09 ar1 1e479bb4
Sec 0 key A cuid 2cbabdd4 nt0 c7ec0827 nr0 464af0e8 ar0 a51501de nt1 6e65b3e1 nr1 a437a982 ar1 2f263c85
Sec 15 key A cuid 2cbabdd4 nt0 947867d8 nr0 9e04eff8 ar0 e8601a4b nt1 7283db65 nr1 58ffbf24 ar1 1d5470f5
Sec 14 key A cuid 2cbabdd4 nt0 9c3394b2 nr0 9a779b81 ar0 f3924024 nt1 8bd03c32 nr1 0ea04321 ar1 08eb593d
Sec 13 key A cuid 2cbabdd4 nt0 49a3e870 nr0 4cc9e38f ar0 ccc0c01d nt1 e75295ac nr1 6a30f809 ar1 a3a58bf5
Sec 12 key A cuid 2cbabdd4 nt0 186f4518 nr0 4e5ed194 ar0 cee54084 nt1 fdd74284 nr1 4f9c31f3 ar1 2632772e
```

Or alternatively, any of the nonces here: <https://github.com/noproto/FlipperMfkey/tree/master/dev/standard_tests>

Nested nonces are not provided, however it works with the FlipperNested application and I am in the process of porting this to the firmware (as well as Mfkey32 optimizations).

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by noproto** [comment]
Pushing an update to this PR within the next 2-3 hrs that reduces RAM usage, uses latest APIs, and fixes a crash. Please don't merge yet.
edit: Ready to be merged!

**Comment by noproto** [comment]
Going to ask that merging is temporarily paused (again). There is a progress bar glitch that sometimes leads to a crash for certain users after some API changes. I believe I know the root cause and I'll fix it today.

**Comment by noproto** [comment]
Ready for merging again.

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
Merged. Sorry for delay.

**Pull request merged**
