### PR TITLE
WS: add protocol EMOS E601x

### PR DESCRIPTION
**Pull request by linusnielsen**
# What's new

- Added the EMOS E601x protocol to the weather station app

# Verification 

- Start the app and trigger an update on the weather station sensor

# Checklist (For Reviewer)

- [X] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by Skorpionm** [comment]
To check you need several ReadRAW sensor records, with different temperatures and humidity

**Comment by linusnielsen** [comment]
> To check you need several ReadRAW sensor records, with different temperatures and humidity

I have tested with my 3 sensors at home, even at subzero temperatures and then compared with the base station readings. It seems to work fine (after fixing my silly refactoring bug with the temperatire sign handling).

I have only tested with the real hardware. Do you mean that there is a way to test with raw .sub files?

**Comment by Skorpionm** [comment]
just write down with a flipper several ReadRAW transmissions of the temperature sensor, at different temperatures and attach these .sub here

**Comment by linusnielsen** [comment]
Here are two .sub files recorded an hour ago.
[subfiles.zip](https://github.com/flipperdevices/flipperzero-good-faps/files/13939271/subfiles.zip)

**Comment by Skorpionm** [comment]
https://github.com/flipperdevices/flipperzero-good-faps/blob/4c85b8fe3daa153c3b5bffe99878ec65af66201d/weather_station/application.fam#L10
need to increase the version

https://github.com/flipperdevices/flipperzero-good-faps/blob/dev/weather_station/.catalog/README.md
add supported protocol to the list

https://github.com/flipperdevices/flipperzero-good-faps/blob/dev/weather_station/.catalog/changelog.md
add changelog

**Comment by linusnielsen** [comment]
Your wish is my command!

**Comment by linusnielsen** [comment]
Anything stopping this from being merged?

**Comment by Skorpionm** [comment]
see my comments in the code above

**Review by skotopes — APPROVED** [review]

**Pull request merged**
