### PR TITLE
Picopass remove sentinel

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Removes sentinel bit from block 7 of iClass, so the value shown is the credential and aligns with output from other tools.
- more info about sentinel: http://www.proxmark.org/files/proxclone.com/iCLASS%20Wiegand%20Data%20Formats_26-37.pdf

# Verification 

- Read a card
- See the value shown has the left most 1 bit removed (ex 0xa goes to 0x2)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by nvx** [comment]
Without the sentinel is there some other way of determining the bit length of the PACS data?

**Comment by bettse** [comment]
The length will be shown along side the credential in the UI.  The full iClass dump is stored, so the raw data is always available.
Screenshot-20230822-132808

**Comment by mistial-dev** [comment]
How would that handle longer credentials, like say the [Open Options 64 Bit Card Format](https://www.ooaccess.com/kb/64bit/)?

**Comment by bettse** [comment]
> How would that handle longer credentials

Not well, but that is a flaw independent of this change.  Anything with a length > 63 would need the sentinel to be in the next block and would end up being misdetected.  I can add it to my todo list.

**Comment by mistial-dev** [comment]
> > How would that handle longer credentials
> 
> Not well, but that is a flaw independent of this change. Anything with a length > 63 would need the sentinel to be in the next block and would end up being misdetected. I can add it to my todo list.

I understand.  It's a bit of an edge case, but there are reasons to do it, which are beyond the scope of this PR discussion.

**Review by skotopes — APPROVED** [review]

**Pull request merged**
