### PR TITLE
[FL-3593] Picopass rework. Part 1

### PR DESCRIPTION
**Pull request by gornekich**
# What's new

- Introduce picopass poller and listener
- Rework reading, writing, emulating, loclass attack with new NFC API

# Verification 

- Test Picopass application. Verify it works as before

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gornekich** [comment]
Hello @bettse, @nvx !
As we agreed, I opened another PR with refactored "worker" part. It is still pretty big, but I think it is much easier for review. I removed old picopass_worker files, introduced picopass_poller and picopass_listener instead. I tried to make as little changes as possible in application part.
Please, let me know if you have any questions.

**Review by bettse — DISMISSED** [review]
I looked over the code (not so much the emulation, since that I'm not as familiar with) and did some tests against cards I have and it looks good to me.  (I'd wait until the other guys get a chance to weigh in before merging though)

**Comment by skotopes** [comment]
@nvx should we wait for you? because firmware is going to be release soon

**Comment by nvx** [comment]
> @nvx should we wait for you? because firmware is going to be release soon

I haven't had a heap of time to look over everything, but of what I have seen so far nothing stands out as an issue so happy to send it for now. I'm sure once users have it there will be edge cases identified that need fixing though, but that's probably the case for the entire NFC refactor.

**Review by skotopes — APPROVED** [review]

**Comment by glennlopez** [comment]
There seems to be a bug (or a feature?) where if you Read an iClass DP or iClass GP then use "Change Key" > "Write Elite" >Save (without editing anything),  it will write to the card but then it will completly render the DP and GP cards unreadable and unwritable (bricking the card?).

**Comment by nvx** [comment]
> There seems to be a bug (or a feature?) where if you Read an iClass DP or iClass GP then use "Change Key" > "Write Elite" >Save (without editing anything), it will write to the card but then it will completly render the DP and GP cards unreadable and unwritable (bricking the card?).

open a separate issue about this and include more details like what the state of the card was

**Comment by bettse** [comment]
And include whether or not the key you set the card to is in your user dictionary

**Pull request merged**
