### PR TITLE
Picopass read improvements

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Better, more picopass specific, UI during dictionary
- Use elite dictionary attack for default read since our system dictionary has 700 keys and otherwise the lack of screen update is confusing

Screenshot-20240113-224344

# Verification 

- Try reading a card, see progress bar

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by bettse** [comment]
@nvx  / @pcunning any thoughts/concerns?

**Comment by nvx** [comment]
sounds like a good change to me, just to confirm it still does standard keys as well first not just elite?

likely won't get a chance to actually test the code for a few days at least

**Comment by bettse** [comment]
> sounds like a good change to me, just to confirm it still does standard keys as well first not just elite?

💯 . it does system standard, user elite, system elite

**Comment by bettse** [comment]
@nvx let me know when you've had a chance to try this (if you want to) and then I'll mark it ready for review

**Comment by nvx** [comment]
> @nvx let me know when you've had a chance to try this (if you want to) and then I'll mark it ready for review
> 

I completely forgot about this, I've had a brief look and seems fine so I reckon send it.

**Review by skotopes — APPROVED** [review]

**Comment by skotopes** [comment]
@bettse I've approved PR. Feel free to merge it.

However there are couple things that bothers me a little bit:
- Leftovers from read scene
- Elite read scene doesn't have `apply card to the back` at the beginning.

**Comment by bettse** [comment]
leaving the read code in for the moment is intentional: I figured if we needed to revert it make the diff simpler/smaller and easier.  I plan to clean it up if we see this working well and don't hear of any problems.

I'll look into the `apply card to the back` and see if I can introduce that.

**Comment by bettse** [comment]
I checked and neither had a literal `apply card to the back`, Read just says "detecting picopass".  I think I'm going to move forward with this, but make a note to work on the flow.  I think it should have some sort of `apply card to the back` at first, and I also think the elite dictionary handling of the tag being removed is less than ideal (seems to treat it like 'skip')

**Pull request merged**
