### PR TITLE
Remove picopass, add readme

### PR DESCRIPTION
**Pull request by bettse**
# What's new

- Remove the picopass app code (moved to https://gitlab.com/bettse/picopass)
- Add readme to folder so anyone looking for code knows where to go

# Verification 

- See code is not present

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by bettse** [comment]
The line that fails is `cp -v $( find . -name '*.fap' ) dist/` and I suspect that `$( find . -name '*.fap' )` is returning nothing and making the cp look like `cp -v dist/`.  I'm guessing this is a result of there being no `fap` created because no source files were touched.  I'm surprised this doesn't happen on PRs where the readme or other non-source files are edited.

**Comment by skotopes** [comment]
Looks like we need @hedger to for that. He will be back in a couple days. Otherwise I can force merge this PR.

**Comment by bettse** [comment]
I have no strong preference; what ever works best for you

**Comment by skotopes** [comment]
Make sense to fix it on CI/CD pipeline side

**Review by hedger — APPROVED** [review]

**Pull request merged**
